import { readdir, readFile, mkdir, writeFile, unlink } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { marked } from 'marked';
import { parse as parseYaml } from 'yaml';

export const siteRoot = fileURLToPath(new URL('../', import.meta.url));
const generatedMarker = '<!-- Generated by scripts/build-blog.mjs; edit Markdown or templates instead. -->';
const slugPattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const reservedSlugs = new Set(['posts', 'templates', 'assets']);

export function isValidSlug(slug) {
    return slugPattern.test(slug) && !reservedSlugs.has(slug);
}

export function escapeHtml(value) {
    return String(value).replace(/[&<>"']/g, character => ({
        '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
    })[character]);
}

function renderTemplate(template, values) {
    return template.replace(/\{\{(\w+)\}\}/g, (_, key) => {
        if (!(key in values)) throw new Error(`Unknown template field: ${key}`);
        return values[key];
    });
}

function parsePost(source, filename) {
    const slug = path.basename(filename, '.md');
    if (!isValidSlug(slug)) {
        throw new Error(`${filename}: use a lowercase filename with words separated by hyphens.`);
    }
    const frontMatter = source.match(/^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/);
    if (!frontMatter) throw new Error(`${filename}: missing YAML front matter between --- lines.`);
    const data = parseYaml(frontMatter[1]);
    if (!data || typeof data !== 'object' || Array.isArray(data)) {
        throw new Error(`${filename}: front matter must be a YAML mapping.`);
    }
    if (typeof data.title !== 'string' || !data.title.trim()) {
        throw new Error(`${filename}: title must be a nonempty string.`);
    }
    if (typeof data.date !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(data.date)) {
        throw new Error(`${filename}: date must use YYYY-MM-DD.`);
    }
    const date = new Date(`${data.date}T00:00:00Z`);
    if (Number.isNaN(date.valueOf()) || date.toISOString().slice(0, 10) !== data.date) {
        throw new Error(`${filename}: date is not a valid calendar date.`);
    }
    if (data.description !== undefined && typeof data.description !== 'string') {
        throw new Error(`${filename}: description must be a string.`);
    }
    if (typeof data.draft !== 'boolean') {
        throw new Error(`${filename}: set draft to true or false.`);
    }
    const markdown = source.slice(frontMatter[0].length).trim();
    if (!data.draft && !markdown) throw new Error(`${filename}: published posts must have content.`);
    return {
        slug,
        title: data.title.trim(),
        date: data.date,
        formattedDate: new Intl.DateTimeFormat('en-US', {
            year: 'numeric', month: 'long', day: 'numeric', timeZone: 'UTC'
        }).format(date),
        description: data.description?.trim() ?? '',
        draft: data.draft,
        html: marked.parse(markdown, { gfm: true })
    };
}

function renderIndex(posts) {
    const heading = `            <header class="page-heading">
                <h1>Blog</h1>
            </header>`;
    if (!posts.length) return `${heading}
            <div class="content-column">
                <p class="empty-state">No posts yet.</p>
            </div>`;
    const items = posts.map(post => `                <li class="post-list-item">
                    <article>
                        <h2><a href="blog/${post.slug}/index.html">${escapeHtml(post.title)}</a></h2>
                        <p class="post-date"><time datetime="${post.date}">${post.formattedDate}</time></p>${post.description ? `
                        <p class="post-description">${escapeHtml(post.description)}</p>` : ''}
                    </article>
                </li>`).join('\n');
    return `${heading}
            <div class="content-column">
                <ul class="post-list">
${items}
                </ul>
            </div>`;
}

function renderPost(post) {
    return `            <article class="blog-post">
                <header class="page-heading">
                    <h1>${escapeHtml(post.title)}</h1>
                    <p class="post-date"><time datetime="${post.date}">${post.formattedDate}</time></p>
                </header>
                <div class="content-column">
                    <div class="post-body">
${post.html.trimEnd()}
                    </div>
                    <p class="back-link"><a href="../../blog.html">All posts</a></p>
                </div>
            </article>`;
}

// Only replace files carrying our generated marker, never a hand-written page.
async function checkGeneratedTarget(filename) {
    try {
        if (!(await readFile(filename, 'utf8')).includes(generatedMarker)) {
            throw new Error(`Refusing to replace a hand-written file: ${filename}`);
        }
    } catch (error) {
        if (error.code !== 'ENOENT') throw error;
    }
}

export async function buildBlog(root = siteRoot) {
    const blogDirectory = path.join(root, 'blog');
    const sourceDirectory = path.join(blogDirectory, 'posts');
    const template = await readFile(path.join(blogDirectory, 'templates/page.html'), 'utf8');
    if (!template.includes(generatedMarker)) {
        throw new Error('Keep the generated-file comment in blog/templates/page.html.');
    }
    const filenames = (await readdir(sourceDirectory)).filter(name => name.endsWith('.md')).sort();
    const allPosts = await Promise.all(filenames.map(async filename => {
        return parsePost(await readFile(path.join(sourceDirectory, filename), 'utf8'), filename);
    }));
    const posts = allPosts.filter(post => !post.draft)
        .sort((a, b) => b.date.localeCompare(a.date) || a.slug.localeCompare(b.slug));
    const outputs = posts.map(post => ({
        filename: path.join(blogDirectory, post.slug, 'index.html'),
        html: renderTemplate(template, {
            root: '../../', title: escapeHtml(post.title),
            description: escapeHtml(post.description || post.title), content: renderPost(post)
        })
    }));
    outputs.push({
        filename: path.join(root, 'blog.html'),
        html: renderTemplate(template, {
            root: '', title: 'Blog',
            description: 'Posts by Karim Abdel Sadek.', content: renderIndex(posts)
        })
    });
    await Promise.all(outputs.map(output => checkGeneratedTarget(output.filename)));
    // Validate and render every source before writing any output.
    for (const output of outputs) {
        await mkdir(path.dirname(output.filename), { recursive: true });
        await writeFile(output.filename, output.html);
    }
    // Unpublish obsolete generated HTML when a post is removed or becomes a draft.
    const publishedSlugs = new Set(posts.map(post => post.slug));
    for (const entry of await readdir(blogDirectory, { withFileTypes: true })) {
        if (!entry.isDirectory() || !isValidSlug(entry.name) || publishedSlugs.has(entry.name)) continue;
        const filename = path.join(blogDirectory, entry.name, 'index.html');
        try {
            if ((await readFile(filename, 'utf8')).includes(generatedMarker)) await unlink(filename);
        } catch (error) {
            if (error.code !== 'ENOENT') throw error;
        }
    }
    return { published: posts.length, drafts: allPosts.length - posts.length };
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
    try {
        const result = await buildBlog();
        console.log(`Built blog.html and ${result.published} post(s); ${result.drafts} draft(s) excluded.`);
    } catch (error) {
        console.error(`Blog build failed: ${error.message}`);
        process.exitCode = 1;
    }
}
