import { readdir, readFile, mkdir, writeFile, unlink } from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { buildBlog, isValidSlug, siteRoot } from './build-blog.mjs';

const rootFiles = ['index.html', 'publications.html', 'undergraduate-research.html', 'blog.html', 'style.css', 'KarimAbdelSadek_CV.pdf'];
const manifestName = '.site-build-manifest.json';
const owner = 'karim-academic-website-build';

function allowedOutput(filename) {
    if (typeof filename !== 'string' || filename.includes('\\') || filename.split('/').some(part => part === '..' || part === '.' || !part)) return false;
    // Accept this retired asset only in an older manifest so the build can safely prune it.
    if (filename === 'publications.js') return true;
    if (rootFiles.includes(filename) || filename.startsWith('images/') || filename.startsWith('blog/assets/')) return true;
    const parts = filename.split('/');
    return parts.length === 3 && parts[0] === 'blog' && isValidSlug(parts[1]) && parts[2] === 'index.html';
}

async function readAssets(root, relative, outputs, optional = false) {
    let entries;
    try {
        entries = await readdir(path.join(root, relative), { withFileTypes: true });
    } catch (error) {
        if (optional && error.code === 'ENOENT') return;
        throw error;
    }
    for (const entry of entries) {
        if (entry.name.startsWith('.')) continue;
        const filename = `${relative}/${entry.name}`;
        if (entry.isSymbolicLink()) throw new Error(`Publish assets must be regular files or directories: ${filename}`);
        if (entry.isDirectory()) await readAssets(root, filename, outputs);
        else if (entry.isFile()) outputs.set(filename, await readFile(path.join(root, filename)));
    }
}

export async function buildSite(root = siteRoot) {
    const blog = await buildBlog(root);
    const outputs = new Map();
    for (const filename of rootFiles) outputs.set(filename, await readFile(path.join(root, filename)));
    await readAssets(root, 'images', outputs);
    await readAssets(root, 'blog/assets', outputs, true);
    for (const entry of await readdir(path.join(root, 'blog'), { withFileTypes: true })) {
        if (!entry.isDirectory() || !isValidSlug(entry.name)) continue;
        const filename = `blog/${entry.name}/index.html`;
        try {
            const content = await readFile(path.join(root, filename));
            if (content.toString().includes('<!-- Generated by scripts/build-blog.mjs; edit Markdown or templates instead. -->')) {
                outputs.set(filename, content);
            }
        } catch (error) {
            if (error.code !== 'ENOENT') throw error;
        }
    }
    const destination = path.join(root, 'dist');
    const manifestPath = path.join(destination, manifestName);
    let previous = [];
    try {
        const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
        if (manifest.owner !== owner || !Array.isArray(manifest.files) || !manifest.files.every(allowedOutput)) {
            throw new Error('dist/ has an invalid build manifest; refusing to modify its files.');
        }
        previous = manifest.files;
    } catch (error) {
        if (error.code !== 'ENOENT') throw error;
        const existing = await readdir(destination).catch(readError => {
            if (readError.code === 'ENOENT') return [];
            throw readError;
        });
        if (existing.length) throw new Error('dist/ contains untracked files; move that directory before building.');
    }
    // Remove only previously managed files, never the directory or unrelated files.
    for (const filename of previous) {
        if (!outputs.has(filename)) {
            await unlink(path.join(destination, filename)).catch(error => {
                if (error.code !== 'ENOENT') throw error;
            });
        }
    }
    for (const [filename, content] of outputs) {
        await mkdir(path.dirname(path.join(destination, filename)), { recursive: true });
        await writeFile(path.join(destination, filename), content);
    }
    await writeFile(manifestPath, `${JSON.stringify({ owner, files: [...outputs.keys()].sort() }, null, 2)}\n`);
    return { ...blog, files: outputs.size };
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
    try {
        const result = await buildSite();
        console.log(`Built dist/ with ${result.published} published post(s) and ${result.files} site files. Markdown sources and drafts are excluded.`);
    } catch (error) {
        console.error(`Site build failed: ${error.message}`);
        process.exitCode = 1;
    }
}
